title       = "xiaoyuzhou"
baseURL     = "https://xiaoyuzhou-cli.tamnd.com/"
description = "Browse Xiaoyuzhou (小宇宙) podcasts and episodes"
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/xiaoyuzhou-cli"
